# Generated by Django 4.2.7 on 2023-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_participant_created_at_participant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='have_rice',
            field=models.BooleanField(default=False),
        ),
    ]
