# Generated by Django 4.2.7 on 2023-11-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_food_have_rice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rice',
            field=models.BooleanField(default=False),
        ),
    ]
