# Generated by Django 4.2.7 on 2023-12-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_order_rice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='have_beverage',
        ),
        migrations.RemoveField(
            model_name='food',
            name='have_dessert',
        ),
        migrations.AddField(
            model_name='beverage',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='food',
            name='restaurant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='رستوران'),
        ),
        migrations.AddField(
            model_name='food',
            name='rice_price',
            field=models.PositiveIntegerField(default=45000, verbose_name='قیمت برنج'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='beverage',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='food',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='food.company', verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='food',
            name='have_rice',
            field=models.BooleanField(default=False, verbose_name='برنج دارد'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
    ]
