# Generated by Django 4.2.7 on 2023-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
